json.id @conversation["id"]
json.user_id @conversation["user_id"]
json.subject @conversation["subject"]
json.participants @conversation["participants"]
json.created_at @conversation["created_at"]
json.updated_at @conversation["updated_at"]
